### ISSUE TITLE
Is Attribute macros supported ?

### ISSUE THREAD

**Issue by nurmohammed840** [bincode-org/virtue#20]
I used this crate and liked it, 

It work great for derive  macro, But does it support [Attribute macros](https://doc.rust-lang.org/reference/procedural-macros.html#attribute-macros) ? 

I read full documentation, Did I missed something, Or this library support this macro ?

Is there any utility library that parse?  function arguments and name, return types, where clause etc... for Attribute macros?

**Comment by VictorKoenders** [comment]
Thanks for trying out virtue, I'm glad you like it!

I haven't gotten around to implementing attribute macros yet. If anyone wants to create a PR for this I'd be happy to merge it. I expect I'll add it at some point but I don't know when yet.

Currently the parser can only handle parsing struct and enum definitions. All code is contained in the [parse](https://github.com/bincode-org/virtue/tree/trunk/src/parse) folder.
