### ISSUE TITLE
Missing `GenEnum` and `GenStruct` outside of a mod

### ISSUE THREAD

**Issue by indietyp** [bincode-org/virtue#23]
Hello, I am currently using virtue in a new project of mine, and so far, it's incredible (but sometimes - understandably - a bit rough around the edges.)

I am currently trying to create structs and enums programmatically. I am now a bit stuck after trying to use `Parse` and seeing how that doesn't provide a TokenStream of the struct or enum it represents via the `Generator.` I'd like to generate a struct and enum on the top level, but it seems like I am unable to do so. I know that you can create a struct via `GenStruct` in a mod, but not an enum.

Are there any plans to add support for `GenEnum` or something similar? How about creating structs and enums outside of a mod?

**Comment by VictorKoenders** [comment]
I think adding a `GenEnum` is a good idea. I also think adding the ability to create structs and enums outside of a mod is a good idea.

If you want you can make a pull request for this, otherwise I'll implement it whenever I get around to it.

**Comment by VictorKoenders** [comment]
This should now be fixed in 0.0.16, please re-open if there are any further  issues
