### ISSUE TITLE
Parser error when using where for trait with comma 

### ISSUE THREAD

**Issue by VictorKoenders** [bincode-org/virtue#35]
Original post by @caliviking 

The following works:
```rs
#[derive(Encode, Decode)]
pub struct MyStruct<T: Clone> {
    pub a: A,
    pub b: B<T>,
}
```

Using a where statement does not work:
```rs
#[derive(Encode, Decode)]
pub struct MyStruct<T>
where T: Clone,
{
    pub a: A,
    pub b: B<T>,
}
```

Error:
``` expected one of `{`, lifetime, or type, found `,` ```

The issue is made worse by the Rust formatter in VS Code insisting that there is a comma after the 'where' declaration. If not, then I could just remove the comma, but it is automatically inserted

**Comment by CaliViking** [comment]
Thanks - I love the functionality in bincode - it is fast and easy to use. Thanks for building it. Looking forward to the 2.0 release.
