### ISSUE TITLE
Mutable consuming self argument

### ISSUE THREAD

**Issue by NightEule5** [bincode-org/virtue#74]
I want to generate a trait impl like this:

```rust
impl Trait for Struct {
    fn something(mut self) -> Self {
        self.field = // mutate something
        self
    }
}
```

`FnBuilder` currently has no intentional way to specify a consuming self argument as mutable; `with_self_arg(FnSelfArg::TakeSelf)` maps to `self`. As a workaround, a self argument can be specified as a normal argument instead:

```rust
fn generate(gen: &mut Generator) {
    gen.impl_for("Trait")
       .generate_fn("something")
       .with_arg("mut self", "Self")
       // ...
}

// generates...
impl Trait for Struct {
    fn something(mut self: Self) -> Self {
        // ...
    }
}
```

**Comment by VictorKoenders** [comment]
Should be easy enough to implement, just add the variant here: https://github.com/bincode-org/virtue/blob/trunk/src/generate/generate_item.rs#L441, and then fix the compile issues
