### ISSUE TITLE
Missing feature to specify attributes on GenStruct

### ISSUE THREAD

**Issue by mscofield0** [bincode-org/virtue#79]
My use case is the following: I would like to derive a macro for my enum and then for each struct-field variant generate an identical struct which the same attributes as the enum (`Clone, Debug, etc...`).

**Comment by VictorKoenders** [comment]
Should be pretty easy:
- Add a field to the [GenStruct](https://github.com/bincode-org/virtue/blob/trunk/src/generate/gen_struct.rs#L8) struct
- Add functions to that struct to add attributes
- Add documentations that also test the output, see [this](https://github.com/bincode-org/virtue/blob/trunk/src/generate/generate_item.rs#L47-L58) for an example

**Comment by NightEule5** [comment]
I'm taking a stab at thing one too, but the API is a bit tricky. I have attributes stored a pairs of the attribute name and a `StreamBuilder` for the rest. Adding a single attribute could look like this:

```rust
impl<'a, P: Parent> GenStruct<'a, P> {
    pub fn with_attribute<T>(
        &mut self,
        name: impl Into<String>,
        value: impl FnOnce(&mut StreamBuilder) -> Result
    ) -> Result<&mut Self> {
        // ...
    }
}
```

If we want to add multiple attributes at once, it's unclear how we'd extend this builder pattern to an `impl IntoIterator`. Another option is to implement `TryFrom` and `From` on `StreamBuilder` for strings and token streams, and use that instead, but that's less flexible than the builder pattern I think.

For fields, it's very cumbersome. For a field with a single attribute, I currently have this to fit with the current field methods:

```rust
pub fn add_field_with_attribute<T>(
    &mut self,
    name: impl Into<String>,
    ty: impl Into<String>,
    attribute_name: impl Into<String>,
    attribute_value: T
) -> crate::Result<&mut Self>
where
    T: FnOnce(&mut StreamBuilder) -> crate::Result
{
    // ...
}
```

You cannot repeat this to add more attributes to the field, unlike `with_attribute`. If `add_field` returned a builder, adding attributes to that would be trivial. A non-breaking, easier to use alternative could be:

```rust
pub fn add_field_with(
    &mut self,
    name: impl Into<String>,
    ty: impl Into<String>,
    build: impl FnOnce(&mut Field) -> crate::Result
) -> crate::Result<&mut Self> {
    // ...
}

struct Field {
    attributes: Vec<(String, StreamBuilder)>,
    // ...
}

impl Field {
    pub fn with_attribute<T>(
        &mut self,
        name: impl Into<String>,
        value: impl FnOnce(&mut StreamBuilder) -> Result
    ) -> Result<&mut Self> {
        // ...
    }
}
```

Thoughts?

**Comment by VictorKoenders** [comment]
> If we want to add multiple attributes at once

Let's do the simple solution first; only 1 attribute at a time. We can come up with something smarter in the future

>  If add_field returned a builder, adding attributes to that would be trivial. 

I'd rather make breaking changes early, especially since virtue is still on `0.0.x`, so feel free to add a `FieldBuilder` or something
